<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AddLight.html" />
    <None Remove="AddSkybox.html" />
    <None Remove="AnimationBlendUI.html" />
    <None Remove="AnimationTimelineUI.html" />
    <None Remove="AssetBrowserPanelUI.html" />
    <None Remove="BrushPanelUI.html" />
    <None Remove="ConsolePanelUI.html" />
    <None Remove="NewMaterial.html" />
    <None Remove="PropertiesPanelUI.html" />
    <None Remove="SkyboxRotateUI.html" />
    <None Remove="SpritePlacementPanelUI.html" />
    <None Remove="TreeViewPanelUI.html" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AddLight.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="AddSkybox.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="AnimationBlendUI.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="AnimationTimelineUI.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="AssetBrowserPanelUI.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="BrushPanelUI.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ConsolePanelUI.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="NewMaterial.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="PropertiesPanelUI.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="SkyboxRotateUI.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="SpritePlacementPanelUI.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="TreeViewPanelUI.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SiegeEngine\SiegeEngine.csproj" />
    <ProjectReference Include="..\Keystone\Keystone.csproj" />
    <ProjectReference Include="..\ReadingChamber\ReadingChamber.csproj" />
  </ItemGroup>

</Project>
