<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReadingChamber\ReadingChamber.csproj" />
    <ProjectReference Include="..\SiegeEngine\SiegeEngine.csproj" />
  </ItemGroup>

</Project>
