<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="NewTerrainForm.html" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="NewTerrainForm.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReadingChamber\ReadingChamber.csproj" />
    <ProjectReference Include="..\SiegeEngine\SiegeEngine.csproj" />
  </ItemGroup>

</Project>
