<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SiegeEngine\SiegeEngine.csproj" />
    <ProjectReference Include="..\MapRoom\MapRoom.csproj" />
    <ProjectReference Include="..\ReadingChamber\ReadingChamber.csproj" />
    <ProjectReference Include="..\ToolChest\ToolChest.csproj" />
  </ItemGroup>

<ItemGroup>
  <None Include="Assets\Configs\**\*.*">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemGroup>

<ItemGroup>
  <None Remove="IDE_UI.html" />
  <None Remove="SaveProjectForm.html" />
  <None Remove="SceneEditorUI.html" />
  <None Remove="ScriptEditorPanelUI.html" />
</ItemGroup>

<ItemGroup>
  <Content Include="IDE_UI.html">
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
  </Content>
  <Content Include="SaveProjectForm.html">
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
  </Content>
  <Content Include="SceneEditorUI.html">
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
  </Content>
  <Content Include="ScriptEditorPanelUI.html">
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
  </Content>
</ItemGroup>

</Project>
