<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
  <TargetFramework>net8.0</TargetFramework>
  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  <Configurations>Debug;Release;Test</Configurations>
</PropertyGroup>

  <ItemGroup>
    <Content Include="$(SolutionDir)Libraries\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>%(Filename)%(Extension)</TargetPath>
    </Content>
    <Content Include="$(SolutionDir)Assets\**\*" CopyToOutputDirectory="PreserveNewest" Link="Assets\%(RecursiveDir)%(Filename)%(Extension)" />
    <Content Remove="C:\Users\ireak\source\repos\RealmFoundry\Castle\Assets\Mods\UnityAssetLoader\**" />
    <Content Remove="C:\repos\RealmFoundry\Castle\Assets\Configs\DevMenu.txt" />
    <PackageReference Include="Silk.NET.GLFW" Version="2.22.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.22.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.1" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
    <PackageReference Include="System.Windows.Extensions" Version="10.0.1" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="C:\Users\ireak\source\repos\RealmFoundry\Castle\Assets\Configs\diagnostics_lists_nav.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
