<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SiegeEngine\SiegeEngine.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>  <!-- Ensure it's a console EXE -->
    <TargetFramework>net9.0</TargetFramework>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>  <!-- Change for your OS/platform -->
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>  <!-- Optional: Compresses the EXE -->
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /Y &quot;$(TargetDir)$(AssemblyName).exe&quot; &quot;$(SolutionDir)Libraries\&quot;" />
  </Target>

</Project>
