<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\SiegeEngine\SiegeEngine.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<UseAppHost>true</UseAppHost>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<PublishTrimmed>false</PublishTrimmed>
		<PublishReadyToRun>false</PublishReadyToRun>
		<!-- Publish to a clean folder to avoid any conflict with Libraries\ -->
		<PublishDir>$(SolutionDir)publish\</PublishDir>
	</PropertyGroup>

</Project>