<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\SiegeEngine\SiegeEngine.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<UseAppHost>true</UseAppHost>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<PublishTrimmed>false</PublishTrimmed>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\Libraries\steam_api64.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy /Y &quot;$(TargetDir)$(AssemblyName).exe&quot; &quot;$(SolutionDir)Libraries\&quot; /I" />
		<Exec Command="xcopy /Y &quot;$(TargetDir)steam_api64.dll&quot; &quot;$(SolutionDir)Libraries\&quot; /I" />
	</Target>

</Project>